// Shared styles for UserResultCard, PostResultCard, LinkResultCard.
import { makeUseStyles, radius, shadow, spacing, typography } from '@kc/ui';

export const useSearchResultCardStyles = makeUseStyles(({ colors, isDark }) => ({
  card: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: isDark ? 1 : 0,
    borderColor: isDark ? colors.border : 'transparent',
    gap: spacing.md,
    marginBottom: spacing.sm,
    ...shadow.card,
    shadowOpacity: isDark ? 0 : shadow.card.shadowOpacity,
    elevation: isDark ? 0 : shadow.card.elevation,
  },
  cardPressed: { backgroundColor: colors.background },
  cardContent: { flex: 1, gap: 2 },
  cardTitle: {
    ...typography.body,
    fontWeight: '600' as const,
    color: colors.textPrimary,
    textAlign: 'right' as const,
  },
  cardHandle: { ...typography.caption, color: colors.textSecondary, textAlign: 'right' as const },
  cardSubtitle: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'right' as const,
    marginTop: 2,
  },
  metaRow: {
    flexDirection: 'row' as const,
    gap: spacing.md,
    marginTop: spacing.xs,
    justifyContent: 'flex-end' as const,
  },
  metaChip: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4 },
  metaText: { ...typography.caption, color: colors.textSecondary, fontSize: 11 },
  avatarWrap: { width: 48, height: 48, borderRadius: 24, overflow: 'hidden' as const, flexShrink: 0 },
  postThumb: { width: 56, height: 56, borderRadius: radius.md, overflow: 'hidden' as const },
  postThumbPlaceholder: {
    backgroundColor: colors.background,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  postTitleRow: { flexDirection: 'row' as const, justifyContent: 'flex-end' as const, marginBottom: 2 },
  typeTag: { paddingHorizontal: spacing.sm, paddingVertical: 2, borderRadius: radius.sm },
  typeTagText: { fontSize: 11, fontWeight: '600' as const },
  linkIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.secondaryLight,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  categoryTag: {
    alignSelf: 'flex-end' as const,
    backgroundColor: colors.primarySurface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: radius.sm,
    marginTop: 2,
  },
  categoryTagText: { fontSize: 11, color: colors.primary, fontWeight: '600' as const },
  linkUrl: {
    ...typography.caption,
    color: colors.textDisabled,
    textAlign: 'right' as const,
    fontSize: 10,
    marginTop: 2,
  },
}));
