// Styles extracted from app/post/[id].tsx to keep the screen under the
// 300-LOC cap (TD-29).
import { makeUseStyles, radius, spacing, typography } from '@kc/ui';

export const usePostDetailStyles = makeUseStyles(({ colors, isDark }) => ({
  container: { flex: 1, backgroundColor: colors.background },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.base,
    backgroundColor: colors.background,
  },
  errorTitle: { ...typography.h3, color: colors.textPrimary, textAlign: 'center' },
  retryBtn: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    backgroundColor: colors.primary,
    borderRadius: radius.full,
  },
  retryText: { ...typography.button, color: colors.textInverse },

  // Image carousel "floats" on the cream backdrop with rounded corners + a
  // soft shadow so it reads as the post's hero — no longer a flush rectangle.
  imageWrap: {
    position: 'relative',
    marginHorizontal: spacing.base,
    marginTop: spacing.base,
    borderRadius: radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: isDark ? 1 : 0,
    borderColor: isDark ? colors.border : 'transparent',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDark ? 0 : 0.06,
    shadowRadius: 8,
    elevation: isDark ? 0 : 2,
  },
  typeTagOverlay: {
    position: 'absolute',
    bottom: spacing.base,
    right: spacing.base,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDark ? 0 : 0.12,
    shadowRadius: 4,
    elevation: isDark ? 0 : 2,
  },
  giveTag: { backgroundColor: colors.giveTagBg },
  requestTag: { backgroundColor: colors.requestTagBg },
  typeTagText: { ...typography.label, color: colors.textPrimary, fontWeight: '700' },

  // Content card — theme-aware surface lifted off the backdrop.
  content: {
    marginHorizontal: spacing.base,
    marginTop: spacing.base,
    padding: spacing.lg,
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    borderWidth: isDark ? 1 : 0,
    borderColor: isDark ? colors.border : 'transparent',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDark ? 0 : 0.05,
    shadowRadius: 6,
    elevation: isDark ? 0 : 1,
  },
  title: {
    ...typography.h2,
    fontSize: 26,
    color: colors.textPrimary,
    textAlign: 'right',
    letterSpacing: -0.3,
    lineHeight: 32,
  },
  category: {
    ...typography.label,
    color: colors.primary,
    textAlign: 'right',
    fontWeight: '700',
    textTransform: 'none' as const,
  },
  conditionRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  conditionLabel: { ...typography.body, color: colors.textSecondary },
  conditionValue: { ...typography.body, color: colors.textPrimary, fontWeight: '600' },
  description: {
    ...typography.body,
    color: colors.textPrimary,
    lineHeight: 24,
    textAlign: 'right',
    paddingTop: spacing.sm,
  },
  locationRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  locationIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.primarySurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationText: { ...typography.body, color: colors.textSecondary, flex: 1, textAlign: 'right' },
  timeText: { ...typography.caption, color: colors.textDisabled, textAlign: 'right' },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.sm },
  authorRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.sm },
  authorInfo: { flex: 1, gap: 2 },
  authorName: { ...typography.body, fontWeight: '600', color: colors.textPrimary, textAlign: 'right' },
  authorCity: { ...typography.caption, color: colors.textSecondary, textAlign: 'right' },

  cta: {
    flexDirection: 'row',
    paddingHorizontal: spacing.base,
    paddingTop: spacing.sm,
    paddingBottom: spacing.base,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  messageBtn: {
    flex: 1,
    height: 56,
    backgroundColor: colors.primary,
    borderRadius: radius.xl,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: isDark ? 0.15 : 0.25,
    shadowRadius: 10,
    elevation: isDark ? 2 : 4,
  },
  messageBtnText: { ...typography.button, fontSize: 16, color: colors.textInverse },
}));
