import { makeUseStyles, radius, spacing, typography } from '@kc/ui';
import { crossAxisAlignStart, layoutDirectionStyle, layoutWritingDirectionStyle, textAlignStart } from '../../src/lib/rtlLayout';
import { rtlTextAlignStart } from '../../src/lib/rtlTextAlignStart';

const cardShadow = (isDark: boolean, shadowColor: string) =>
  isDark
    ? { shadowOpacity: 0, elevation: 0 }
    : {
        shadowColor,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
      };

export const useCreatePostStyles = makeUseStyles(({ colors, isDark }) => ({
  container: { flex: 1, backgroundColor: colors.surfaceCream },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    backgroundColor: 'transparent',
  },
  headerClose: { padding: spacing.xs },
  headerTitle: { ...typography.h3, color: colors.textPrimary, fontSize: 20, letterSpacing: -0.3 },
  publishBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
    borderRadius: radius.lg,
    minWidth: 72,
    alignItems: 'center' as const,
  },
  publishBtnFooter: { alignSelf: 'stretch' as const, marginTop: spacing.md },
  publishBtnText: { ...typography.button, color: colors.textInverse },
  scroll: { flex: 1 },
  // `paddingBottom` is supplied dynamically by `useShellTabBarScrollInset()`
  // so the publish CTA clears the floating tab-bar pill (FR-RESP-006).
  scrollContent: { padding: spacing.base, gap: spacing.base },
  typeToggle: {
    flexDirection: 'row' as const,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: isDark ? 1 : 1.5,
    borderColor: colors.border,
    overflow: 'hidden' as const,
    ...cardShadow(isDark, colors.shadow),
  },
  typeBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    alignItems: 'center' as const,
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    gap: spacing.xs,
  },
  typeBtnActive: { backgroundColor: colors.requestTagBg },
  typeBtnActiveGive: { backgroundColor: colors.giveTagBg },
  typeBtnText: { ...typography.button, color: colors.textSecondary },
  typeBtnTextActive: { color: colors.textPrimary },
  section: { gap: spacing.xs },
  sectionLabel: { ...typography.label, color: colors.textSecondary, textAlign: rtlTextAlignStart },
  required: { color: colors.error },
  input: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: isDark ? 1 : 1.5,
    borderColor: colors.border,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    ...typography.body,
    color: colors.textPrimary,
    minHeight: 52,
  },
  textarea: { minHeight: 100, textAlignVertical: 'top' as const, paddingTop: spacing.md },
  charCount: { ...typography.caption, color: colors.textDisabled, textAlign: 'left' as const },
  sectionHint: {
    ...typography.caption,
    color: colors.error,
    textAlign: rtlTextAlignStart,
    lineHeight: 18,
    ...layoutWritingDirectionStyle(),
  },
  streetRow: { flexDirection: 'row' as const, gap: spacing.sm, alignItems: 'stretch' as const },
  streetInputStreet: { flex: 2, minWidth: 0 },
  streetInputHouse: { flex: 1, minWidth: 0, maxWidth: 120 },
  chips: { flexDirection: 'row' as const },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    borderWidth: isDark ? 1 : 1.5,
    borderColor: colors.border,
    marginLeft: spacing.sm,
    backgroundColor: colors.surface,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { ...typography.label, color: colors.textSecondary },
  chipTextActive: { color: colors.textInverse },
  conditionRow: { flexDirection: 'row' as const, gap: spacing.sm },
  conditionBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: radius.lg,
    borderWidth: isDark ? 1 : 1.5,
    borderColor: colors.border,
    alignItems: 'center' as const,
    backgroundColor: colors.surface,
  },
  conditionBtnActive: { backgroundColor: colors.primarySurface, borderColor: colors.primary },
  conditionText: { ...typography.label, color: colors.textSecondary },
  conditionTextActive: { color: colors.primary },
  exposureAccordion: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden' as const,
    ...layoutDirectionStyle(),
  },
  exposureAccordionHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.base,
  },
  exposureAccordionTitle: {
    ...typography.caption,
    fontWeight: '600' as const,
    color: colors.textPrimary,
    textAlign: textAlignStart(),
    flex: 1,
    ...layoutWritingDirectionStyle(),
  },
  exposureAccordionBody: {
    paddingHorizontal: spacing.base,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  exposureIntro: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: rtlTextAlignStart,
    lineHeight: 18,
    ...layoutWritingDirectionStyle(),
  },
  counterpartyPrivacy: {
    gap: spacing.xs,
    padding: spacing.sm,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  counterpartyPrivacyHeader: { alignItems: crossAxisAlignStart },
  counterpartyPrivacyTitle: {
    ...typography.caption,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    textAlign: textAlignStart(),
    ...layoutWritingDirectionStyle(),
  },
  counterpartyPrivacyRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: spacing.sm,
  },
  counterpartyPrivacyLabel: {
    ...typography.caption,
    flex: 1,
    color: colors.textPrimary,
    textAlign: textAlignStart(),
    ...layoutWritingDirectionStyle(),
  },
  counterpartyPrivacyHint: {
    ...typography.caption,
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: textAlignStart(),
    lineHeight: 16,
    ...layoutWritingDirectionStyle(),
  },
}));
