export { getSupabaseClient, resetSupabaseClient, setOnForbiddenCallback } from './client';
export type { SupabaseAuthStorage } from './client';
export type { Database } from './database.types';

export { SupabaseAuthService } from './auth/SupabaseAuthService';
export { SupabaseUserRepository } from './users/SupabaseUserRepository';
export { SupabaseCityRepository } from './cities/SupabaseCityRepository';
export { SupabaseStreetRepository } from './streets/SupabaseStreetRepository';
export { SupabasePostRepository } from './posts/SupabasePostRepository';
export { SupabaseSavedPostsRepository } from './posts/SupabaseSavedPostsRepository';
export { SupabaseChatRepository } from './chat/SupabaseChatRepository';
export { SupabaseChatRealtime } from './chat/SupabaseChatRealtime';
export { SupabaseUserRealtime } from './users/SupabaseUserRealtime';
export { SupabaseFeedRealtime } from './feed/SupabaseFeedRealtime';
export { SupabaseStatsRepository } from './stats/SupabaseStatsRepository';
export { SupabaseAboutRepository } from './about/SupabaseAboutRepository';
export { SupabaseReportRepository } from './reports/SupabaseReportRepository';
export { SupabaseModerationAdminRepository } from './moderation/SupabaseModerationAdminRepository';
export { SupabaseAccountGateRepository } from './auth/SupabaseAccountGateRepository';
export { SupabaseDonationLinksRepository } from './donations/SupabaseDonationLinksRepository';
export { SupabaseSearchRepository } from './search/SupabaseSearchRepository';
export { SupabaseDeviceRepository } from './notifications/SupabaseDeviceRepository';
export { SupabaseLegalDocumentRepository } from './legal/SupabaseLegalDocumentRepository';
export { LegalDocumentCache, type AsyncKVStorage } from './legal/legalCache';
export * from './admin/SupabaseAdminRoleRepository';
export * from './admin/SupabaseAdminTaskRepository';
export * from './admin/SupabaseAdminContentRepository';
export * from './admin/SupabaseTimesheetsRepository';
export * from './admin/SupabaseFinanceLedgerRepository';
export * from './admin/SupabaseFinanceAccountsRepository';
export * from './admin/SupabaseCrmContactsRepository';
export * from './admin/SupabaseOrgApplicationsRepository';
export * from './org/SupabaseOrganizationRepository';
export * from './reports/SupabaseReportsRepository';
export { SupabaseRideListingRepository } from './rides/SupabaseRideListingRepository';
export { SupabaseRideParticipantRepository } from './rides/SupabaseRideParticipantRepository';
export { SupabaseRideTemplateRepository } from './rides/SupabaseRideTemplateRepository';
export { SupabaseRideStopsRepository } from './rides/SupabaseRideStopsRepository';
export { SupabaseRideEmergencyRepository } from './rides/SupabaseRideEmergencyRepository';
export { SupabaseRideRatingRepository } from './rides/SupabaseRideRatingRepository';
export { SupabaseDriverDeclarationRepository } from './rides/SupabaseDriverDeclarationRepository';
export { SupabaseRidesRealtime } from './rides/SupabaseRidesRealtime';
export { SupabaseSurveyRepository } from './survey/SupabaseSurveyRepository';
export { SupabasePublicResearchRepository } from './research/SupabasePublicResearchRepository';
