import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    maxWidth: 480,
    width: '100%',
    direction: 'rtl',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#c8323a',
    textAlign: 'right',
    marginBottom: 14,
  },
  bulletList: {
    marginBottom: 12,
  },
  bullet: {
    fontSize: 15,
    lineHeight: 22,
    color: '#222',
    textAlign: 'right',
    marginBottom: 4,
  },
  chatsRetention: {
    fontSize: 15,
    fontWeight: '600',
    color: '#222',
    textAlign: 'right',
    marginBottom: 10,
    backgroundColor: '#fff7e6',
    padding: 10,
    borderRadius: 8,
  },
  warning: {
    fontSize: 13,
    lineHeight: 20,
    color: '#666',
    textAlign: 'right',
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    color: '#666',
    textAlign: 'right',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'web' ? 10 : 8,
    fontSize: 16,
    textAlign: 'right',
    marginBottom: 16,
    color: '#222',
  },
  buttonsRow: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    gap: 12,
  },
  buttonDelete: {
    flex: 1,
    backgroundColor: '#c8323a',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDeleteDisabled: {
    backgroundColor: '#dca1a4',
  },
  buttonDeleteText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  buttonCancel: {
    flex: 1,
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonCancelText: {
    color: '#222',
    fontSize: 16,
    fontWeight: '600',
  },
  errorBanner: {
    backgroundColor: '#fde6e8',
    borderColor: '#c8323a',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  errorBannerText: {
    color: '#9a1d24',
    fontSize: 14,
    textAlign: 'right',
  },
  errorBannerCritical: {
    backgroundColor: '#c8323a',
  },
  errorBannerCriticalText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  blockedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#c8323a',
    textAlign: 'right',
    marginBottom: 8,
  },
  blockedBody: {
    fontSize: 15,
    color: '#222',
    textAlign: 'right',
    marginBottom: 16,
  },
});
