import { makeUseStyles, radius, spacing, typography } from '@kc/ui';

export const useSearchablePickerStyles = makeUseStyles(({ colors, isDark }) => ({
  field: {
    height: 50,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    borderWidth: isDark ? 1 : 1.5,
    borderColor: colors.border,
    paddingHorizontal: spacing.base,
    justifyContent: 'center' as const,
  },
  fieldDisabled: { opacity: 0.5 },
  disabledHelper: {
    ...typography.label,
    color: colors.textSecondary,
    textAlign: 'right' as const,
    marginTop: spacing.xs,
  },
  value: { ...typography.body, color: colors.textPrimary, textAlign: 'right' as const },
  valuePlaceholder: { color: colors.textDisabled },
  modalRoot: { flex: 1 },
  backdropPressable: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.overlay,
  },
  sheetOuter: { flex: 1, justifyContent: 'flex-end' as const },
  sheet: {
    height: '70%',
    backgroundColor: colors.surfaceRaised,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    paddingTop: spacing.base,
    paddingHorizontal: spacing.base,
    borderWidth: isDark ? 1 : 0,
    borderColor: isDark ? colors.border : 'transparent',
  },
  sheetTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    textAlign: 'center' as const,
    marginBottom: spacing.sm,
  },
  search: {
    minHeight: 44,
    textAlign: 'right' as const,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.base,
    marginBottom: spacing.sm,
    ...typography.body,
    color: colors.textPrimary,
  },
  statusRow: { paddingVertical: spacing.lg, alignItems: 'center' as const },
  errorBlock: { alignItems: 'center' as const, paddingVertical: spacing.md },
  errorText: {
    ...typography.body,
    color: colors.error,
    textAlign: 'center' as const,
    paddingVertical: spacing.sm,
  },
  retryButton: {
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.primarySurface,
  },
  retryLabel: {
    ...typography.body,
    color: colors.primary,
    fontWeight: '600' as const,
    textAlign: 'center' as const,
  },
  emptyText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    paddingVertical: spacing.lg,
  },
  row: {
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  rowText: { ...typography.body, color: colors.textPrimary, textAlign: 'right' as const },
  freeTextRow: { backgroundColor: colors.primarySurface },
  freeTextLabel: {
    ...typography.body,
    color: colors.primary,
    textAlign: 'right' as const,
    fontWeight: '600' as const,
  },
}));
